### PR TITLE
1123 fix calendar not closing when closing map layers control

### LINKED ISSUE #1123: MapLayersControl calendar not properly closing when input losing focus
FE PR: https://github.com/HSLdevcom/jore-map-ui/pull/1182

### PR DESCRIPTION
**Pull request by Divinare**
Closes #1123 

Now it closes calendar on hover

Still calendar doesn't get closed when clicked outside (inside mapLayersControl) (that onOutsideClick() method doesn't somehow get triggered. I guess the reason is that the mapLayersControl is being rendered inside react-leaflet). A hack might be needed to fix that, so far I don't see reason to fix it

### CODE REVIEW

**Comment by Divinare** [comment]
Can be reviewed now.

Fixed closing calendar in mapLayersControl. Had to use setTimeout "hack" because onBlur event came before year selection event in calendar. Should work perfectly now however.

**Comment by ahjyrkia** [comment]
Changing month/year triggers onBlur (or something) and closes the calendar

**Comment by Divinare** [comment]
Should work now. You can't close calendar with click in mapLayers menu but hovering out from the mapLayers menu closes calendar.

**Comment by ahjyrkia** [comment]
Reviewed. Changes ok

**Pull request merged**
