### PR TITLE
916 automatically fill stop postal number and address

### PR DESCRIPTION
**Pull request by Divinare**
* Implemented reverse geocoding using openstreetmap API: https://nominatim.org/release-docs/develop/api/Reverse/
* encountered a problem with current state of ViewFormBase: isEditingDisabled had to be moved to store.
    * also countered other problem: fetching address data in nodeStore -> need to validate stop properties in stop form -> had to implement 3 watch functions to stop form (addressFi, addressSw, postalNumber) to validate those fields changed by address fetch. Couldn't validate those properties in nodeStore (which would have been ideal solution), but instead had to listen changes to validate those properties in stop form because stop form has access to its invalidPropertiesMap
    -> this brought in mind an idea: what if viewFormBase would be in a store that each view would use. This one should be implemented in other card: https://github.com/HSLdevcom/jore-map-ui/issues/1019
* isEditingDisabled had to be moved to nodeStore because it was hard to watch when it changed to fetch address after that (however I could try to revert it back to viewFormBase since codebase changed slightly (address fetch is in nodeStore etc.)
    * refactoring task to move it out from VIewFromBase in other views as well: https://github.com/HSLdevcom/jore-map-ui/issues/1022
---

**Test this task carefully. Try to test every single variation. There are many ways that stop form could break.**

A few bugs fixed here:

Fixed stop form invalidPropertiesMap not reseting:
(test at stage environment)
1) open random stop form
2) change name of a stop to > 20 letters
3) click "isEditingDisabled"
-> error msg stays on screen

Fixed new stop form now validating properly
(test at stage environment)
1) open new stop form with "new stop tool"
2) change name field so that validation passes
3) create a new stop again
-> name field is not validated even though the field is empty

### CODE REVIEW

**Comment by Divinare** [comment]
WIP: postNumber should be queried from digitransit API instead. Openstreetmap's postnumber is not that reliable

**Comment by Divinare** [comment]
This can now be reviewed.

**Comment by ahjyrkia** [comment]
Bug with the stop form:

1) Create new node called "first".
2) Create another new node called "second".
3) Refresh page (and url parameters).
4) Click the "first" node on map and then click the "second" node.
5) Close "second" node by pressing "X" on top right of sidepanel.
6) The map focuses on "first" node and opens it but it has values from the "second" node. 

This problem persists even if you try to open a different node and come back to the "first" node.

**Comment by Divinare** [comment]
Stop form bug will be fixed here: https://github.com/HSLdevcom/jore-map-ui/issues/1034

**Comment by ahjyrkia** [comment]
Works and reviewed. A bug found that is made in to its own issue

**Pull request merged**
