### PR TITLE
Fix vulnerability warnings

### PR DESCRIPTION
**Pull request by kronken**
Fix vulnerability warnings and remove package-lock.json, since we are using yarn

### CODE REVIEW

**Comment by neodyymi** [comment]
`yarn audit` gave me one more thing to fix
```
yarn audit v1.12.3
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ Missing Origin Validation                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ webpack-dev-server                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=3.1.6                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ webpack-dev-server                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ webpack-dev-server                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/725                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
1 vulnerabilities found - Packages audited: 32283
Severity: 1 High
Done in 2.42s.
```

Should this be done now too?

**Comment by kronken** [comment]
> `yarn audit` gave me one more thing to fix
> 
> ```
> yarn audit v1.12.3
> ┌───────────────┬──────────────────────────────────────────────────────────────┐
> │ high          │ Missing Origin Validation                                    │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ Package       │ webpack-dev-server                                           │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ Patched in    │ >=3.1.6                                                      │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ Dependency of │ webpack-dev-server                                           │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ Path          │ webpack-dev-server                                           │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ More info     │ https://nodesecurity.io/advisories/725                       │
> └───────────────┴──────────────────────────────────────────────────────────────┘
> 1 vulnerabilities found - Packages audited: 32283
> Severity: 1 High
> Done in 2.42s.
> ```
> Should this be done now too?

This seems to a bit more complicated issue, the upgrade of webpack-dev-server was not atleast working out of the box. So, maybe we don't have to fix this in this task.

**Comment by kronken** [comment]
https://github.com/HSLdevcom/jore-map-ui/issues/391

**Comment by neodyymi** [comment]
Review ok.

**Pull request merged**
